/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MemoriaVentana.java
 *
 * Created on 5/11/2011, 08:09:32 AM
 */
package memoria;

import javax.swing.JButton;

/**
 *
 * @author admin
 */
public class MemoriaCliente extends javax.swing.JFrame {

    MemoriaInterface memoria;           // SE DECLARA DEL TIPO INTERFACE
    int contadorTarjetasAbiertas;
    String valorAnterior;
    private javax.swing.JButton botonAnterior;

    /** Creates new form MemoriaVentana */
    public MemoriaCliente() {
        // SE INSTANCIA COMO MEMORIA IMPLEMENTACION, UNA INTERFACE NO SE PUEDE
        // INSTANCIAR.
        memoria = new MemoriaTCPCliente("localhost", 2000);
        contadorTarjetasAbiertas = 0;
        valorAnterior = "0";
        botonAnterior = new JButton();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton00 = new javax.swing.JButton();
        boton01 = new javax.swing.JButton();
        boton02 = new javax.swing.JButton();
        boton03 = new javax.swing.JButton();
        boton10 = new javax.swing.JButton();
        boton11 = new javax.swing.JButton();
        boton12 = new javax.swing.JButton();
        boton13 = new javax.swing.JButton();
        boton20 = new javax.swing.JButton();
        boton21 = new javax.swing.JButton();
        boton22 = new javax.swing.JButton();
        boton23 = new javax.swing.JButton();
        boton30 = new javax.swing.JButton();
        boton31 = new javax.swing.JButton();
        boton32 = new javax.swing.JButton();
        boton33 = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        botonTiempo = new javax.swing.JButton();
        labelTiempo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boton00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton00MouseClicked(evt);
            }
        });
        boton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton00ActionPerformed(evt);
            }
        });

        boton01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton01MouseClicked(evt);
            }
        });

        boton02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton02MouseClicked(evt);
            }
        });
        boton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton02ActionPerformed(evt);
            }
        });

        boton03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton03MouseClicked(evt);
            }
        });
        boton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton03ActionPerformed(evt);
            }
        });

        boton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton10MouseClicked(evt);
            }
        });

        boton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton11MouseClicked(evt);
            }
        });

        boton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton12MouseClicked(evt);
            }
        });

        boton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton13MouseClicked(evt);
            }
        });
        boton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton13ActionPerformed(evt);
            }
        });

        boton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton20MouseClicked(evt);
            }
        });

        boton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton21MouseClicked(evt);
            }
        });

        boton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton22MouseClicked(evt);
            }
        });

        boton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton23MouseClicked(evt);
            }
        });

        boton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton30MouseClicked(evt);
            }
        });

        boton31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton31MouseClicked(evt);
            }
        });

        boton32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton32MouseClicked(evt);
            }
        });

        boton33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton33MouseClicked(evt);
            }
        });

        nuevo.setText("Nuevo");
        nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoMouseClicked(evt);
            }
        });
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        botonTiempo.setText("Ver Tiempo");
        botonTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTiempoActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton32, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton33, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boton21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(boton00, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boton11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boton01, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boton12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boton02, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(boton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(boton03, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boton23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonTiempo)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(53, 53, 53)
                .addComponent(labelTiempo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(labelTiempo)
                .addContainerGap(375, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevo)
                    .addComponent(botonTiempo)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(boton00, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(boton10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(boton02, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(boton12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton03, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boton01, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton32, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton33, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoActionPerformed

    private void boton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton00ActionPerformed

    private void nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMouseClicked
        memoria.IniciarJuego();
    }//GEN-LAST:event_nuevoMouseClicked

    private void boton00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton00MouseClicked
        String valor = "" + memoria.MostrarTarjeta(0, 0);
        boton00.setText(valor);


        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton00;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton00.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton00.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton00MouseClicked

    private void boton01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton01MouseClicked
        String valor = "" + memoria.MostrarTarjeta(0, 1);
        boton01.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton01;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton01.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton01.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };

    }//GEN-LAST:event_boton01MouseClicked

    private void boton02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton02MouseClicked
        String valor = "" + memoria.MostrarTarjeta(0, 2);
        boton02.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton02;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton02.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton02.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };

    }//GEN-LAST:event_boton02MouseClicked

    private void boton03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton03MouseClicked
        String valor = "" + memoria.MostrarTarjeta(0, 3);
        boton03.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton03;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton03.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton03.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton03MouseClicked

    private void boton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton10MouseClicked
        String valor = "" + memoria.MostrarTarjeta(1, 0);
        boton10.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton10;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton10.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton10.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton10MouseClicked

    private void boton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton11MouseClicked
        String valor = "" + memoria.MostrarTarjeta(1, 1);
        boton11.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton11;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton11.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton11.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton11MouseClicked

    private void boton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton12MouseClicked
        String valor = "" + memoria.MostrarTarjeta(1, 2);
        boton12.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton12;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton12.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton12.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton12MouseClicked

    private void boton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton13MouseClicked
        String valor = "" + memoria.MostrarTarjeta(1, 3);
        boton13.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton13;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton13.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton13.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton13MouseClicked

    private void boton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton20MouseClicked
        String valor = "" + memoria.MostrarTarjeta(2, 0);
        boton20.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton20;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton20.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton20.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton20MouseClicked

    private void boton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton21MouseClicked
        String valor = "" + memoria.MostrarTarjeta(2, 1);
        boton21.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton21;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton21.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton21.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton21MouseClicked

    private void boton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton22MouseClicked
        String valor = "" + memoria.MostrarTarjeta(2, 2);
        boton22.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton22;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton22.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton22.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton22MouseClicked

    private void boton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton23MouseClicked
        String valor = "" + memoria.MostrarTarjeta(2, 3);
        boton23.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton23;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton23.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton23.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton23MouseClicked

    private void boton30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton30MouseClicked
        String valor = "" + memoria.MostrarTarjeta(3, 0);
        boton30.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton30;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton30.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton30.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton30MouseClicked

    private void boton31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton31MouseClicked
        String valor = "" + memoria.MostrarTarjeta(3, 1);
        boton31.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton31;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton31.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton31.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton31MouseClicked

    private void boton32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton32MouseClicked
        String valor = "" + memoria.MostrarTarjeta(3, 2);
        boton32.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton32;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton32.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton32.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton32MouseClicked

    private void boton33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton33MouseClicked
        String valor = "" + memoria.MostrarTarjeta(3, 3);
        boton33.setText(valor);

        if (contadorTarjetasAbiertas == 0) {
            valorAnterior = valor;
            botonAnterior = boton33;
            contadorTarjetasAbiertas = 1;
        } else {
            if (valor.equals(valorAnterior)) {
                boton33.setText("OK");
                botonAnterior.setText("OK");
            } else {
                boton33.setText("");
                botonAnterior.setText("");
            }
            contadorTarjetasAbiertas = 0;
        };
    }//GEN-LAST:event_boton33MouseClicked

    private void botonTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTiempoActionPerformed
        String valor = "" + memoria.VerTiempo();
        labelTiempo.setText(valor + "seg.");
    }//GEN-LAST:event_botonTiempoActionPerformed

private void boton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton02ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_boton02ActionPerformed

private void boton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton03ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_boton03ActionPerformed

private void boton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton13ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_boton13ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    memoria.Salir();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoriaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoriaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoriaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoriaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MemoriaCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton00;
    private javax.swing.JButton boton01;
    private javax.swing.JButton boton02;
    private javax.swing.JButton boton03;
    private javax.swing.JButton boton10;
    private javax.swing.JButton boton11;
    private javax.swing.JButton boton12;
    private javax.swing.JButton boton13;
    private javax.swing.JButton boton20;
    private javax.swing.JButton boton21;
    private javax.swing.JButton boton22;
    private javax.swing.JButton boton23;
    private javax.swing.JButton boton30;
    private javax.swing.JButton boton31;
    private javax.swing.JButton boton32;
    private javax.swing.JButton boton33;
    private javax.swing.JButton botonTiempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelTiempo;
    private javax.swing.JButton nuevo;
    // End of variables declaration//GEN-END:variables
}
